### ISSUE TITLE
Corrupted UTF-16 email message terminate all MailScanner subprocesses with error

### ISSUE THREAD

**Issue by laser84** [MailScanner/v5#379]
The corrupted UTF-16 email message terminate all MailScanner subprocesses with error:
`UTF-16:Unrecognised BOM 4e00 at /usr/local/share/perl5/MIME/WordDecoder.pm line 616`

This has the effect that the queue begins to overflow.
The corrupted message must be manually release, e.g. with command:
`postsuper -H <MAIL_ID>`

This behavior was noticed on Centos 7.5 and 7.6 with MailScanner v5.1.1.

**Comment by shawniverson** [comment]
This should be resolved in 5.1.3.

https://github.com/MailScanner/v5/issues/253

**Comment by laser84** [comment]
Hi,
I updated MailScanner to v5.1.3-2, but bug still persistent.

**Comment by shawniverson** [comment]
@laser84 Do you have a snippet of the UTF-16 email message you can share?  (Please sanitize the message before posting.)

**Comment by laser84** [comment]
Snippet of UTF-16 email message:

`From: <noreply@email.local>
To: <test@email.local>
Subject: =?utf-16?B?TgBhAHMAdABhAHYAZQBuAO0AIABvAHAAcgDhAHYAbgAbAW4A?=
 =?utf-16?B?7QAsACAAcABvAH4BYQBkAGEAdgBlAGsAIABTAGgAYQByAGUAUABvAGkA?=
 =?utf-16?B?bgB0ACAALQAgAEEAcABsAGkAawBhAGMAZQAgAE0AUwBTAFEATAA=?=
Content-Type: text/plain; charset="utf-16"
Content-Transfer-Encoding: base64

RABvAGIAcgD9ACAAZABlAG4ALAAgAAoACgBWAGEAYQFlACAAfgHhAGQAbwBzAHQAIAAwADEAMgAz
ADQAIABkAG8AIABhAHAAbABpAGsAYQBjAGUAIABNAFMAUwBRAEwAIABiAHkAbABhACAAdgB5AFkB
ZQBhAWUAbgBhAC4AIABQAHIAbwAgAGQAbwBrAG8AbgANAWUAbgDtACAAcAByAG8AYwBlAHMAdQAg
AGoAZQAgAG4AZQB6AGIAeQB0AG4A6QAgAHMAZQAgAHoAbgBvAHYAdQAgAHAAWQFpAGgAbADhAHMA
aQB0ACAAZABvACAAVwBpAG4AZABvAHcAcwAuAAoACgBWACAAcABZAe0AcABhAGQAGwEgAG4AZQBq
AGEAcwBuAG8AcwB0AO0AIABuAOEAcwAgAGsAbwBuAHQAYQBrAHQAdQBqAHQAZQAgAG4AYQAgAG4A
YQBhAWUAbQAgAGUAbQBhAGkAbAB1AC4ACgAKAFMAIABwAG8AegBkAHIAYQB2AGUAbQAsAAoACgBJ
AFQAIABIAGUAbABwAGQAZQBzAGsACgA=`

**Comment by msapiro** [comment]
Are you saying this message is corrupted because the continuation lines of the Subject: header do not have leading whitespace? If I change that to
```
Subject: =?utf-16?B?TgBhAHMAdABhAHYAZQBuAO0AIABvAHAAcgDhAHYAbgAbAW4A?=
 =?utf-16?B?7QAsACAAcABvAH4BYQBkAGEAdgBlAGsAIABTAGgAYQByAGUAUABvAGkA?=
 =?utf-16?B?bgB0ACAALQAgAEEAcABsAGkAawBhAGMAZQAgAE0AUwBTAFEATAA=?=
```
The message appears to be valid.

I have run the message through MailScanner 5.1.3 both with and without the leading space in the Subject continuation lines. Neither one caused a problem with MailScanner. Of course, without the leading spaces, the body is garbled because the headers stop at
```
Subject: =?utf-16?B?TgBhAHMAdABhAHYAZQBuAO0AIABvAHAAcgDhAHYAbgAbAW4A?=
```
and the remainder
```
=?utf-16?B?7QAsACAAcABvAH4BYQBkAGEAdgBlAGsAIABTAGgAYQByAGUAUABvAGkA?=
=?utf-16?B?bgB0ACAALQAgAEEAcABsAGkAawBhAGMAZQAgAE0AUwBTAFEATAA=?=
Content-Type: text/plain; charset="utf-16"
Content-Transfer-Encoding: base64

RABvAGIAcgD9ACAAZABlAG4ALAAgAAoACgBWAGEAYQFlACAAfgHhAGQAbwBzAHQAIAAwADEAMgAz
ADQAIABkAG8AIABhAHAAbABpAGsAYQBjAGUAIABNAFMAUwBRAEwAIABiAHkAbABhACAAdgB5AFkB
ZQBhAWUAbgBhAC4AIABQAHIAbwAgAGQAbwBrAG8AbgANAWUAbgDtACAAcAByAG8AYwBlAHMAdQAg
AGoAZQAgAG4AZQB6AGIAeQB0AG4A6QAgAHMAZQAgAHoAbgBvAHYAdQAgAHAAWQFpAGgAbADhAHMA
aQB0ACAAZABvACAAVwBpAG4AZABvAHcAcwAuAAoACgBWACAAcABZAe0AcABhAGQAGwEgAG4AZQBq
AGEAcwBuAG8AcwB0AO0AIABuAOEAcwAgAGsAbwBuAHQAYQBrAHQAdQBqAHQAZQAgAG4AYQAgAG4A
YQBhAWUAbQAgAGUAbQBhAGkAbAB1AC4ACgAKAFMAIABwAG8AegBkAHIAYQB2AGUAbQAsAAoACgBJ
AFQAIABIAGUAbABwAGQAZQBzAGsACgA=
```
becomes the message body.

**Comment by laser84** [comment]
Sorry, my mistake, I add to my previous comment message to a code block and message contains spaces on the beginning line now.

The error still persists.

**Comment by msapiro** [comment]
As I said, I have run this message through MailScanner 5.1.3-2 with no problem. I have tried both with the default
```
Scanned Modify Subject = no
```
and with both
```
Scanned Modify Subject = start
```
and
```
Scanned Modify Subject = end
```
In all three cases the message is processed by MailScanner with no problem and in the latter two cases the `{scanned}` tag is added appropriately to the subject.

Further, the message you provide does not appear to be corrupt in any way. These seem to be perfectly valid utf-16 encodings of the Subject:
```
Nastavení oprávnění, požadavek SharePoint - Aplikace MSSQL
```
and body
```
Dobrý den, 

Vaše žádost 01234 do aplikace MSSQL byla vyřešena. Pro dokončení procesu je nezbytné se znovu přihlásit do Windows.

V případě nejasností nás kontaktujte na našem emailu.

S pozdravem,

IT Helpdesk

```

**Comment by shawniverson** [comment]
@laser84 What version of MIME::Tools do you have installed?  I agree with @msapiro that the sample you provided is valid utf-16.  

```
perl -MMIME::Tools -e 'print $MIME::Tools::VERSION ."\n";'
```

**Comment by laser84** [comment]
@shawniverson Command returned version 5.509.

I checked that it was a version downloaded with MailScanner to /usr/local/share/perl5/MIME (override base version 5.505 installed from repository EPEL). This is the last available version of MIME:Tools installed by the command `perl -MCPAN -e "CPAN::Shell->force(qw(install MIME::Tools))`.

**Comment by jtempir** [comment]
I have the same problem. 
Which linux distribution and MTA did you use for testing this problem?

**Comment by shawniverson** [comment]
@jtempir @laser84 Are either of you able and willing to send me a complete sample with message headers as an attachment?  I think I need to see the entire message to get to the bottom of this problem.  If so, you can email it to shawniverson@gmail.com.

**Comment by jtempir** [comment]
Unfortunately, I can't forward any email to you.
I will describe the procedure that will result in a Mailscanner error using the sample above.
I will skip the installation and setup of CentOS 7, Postfix and Mailscanner.

Save email from @laser84 to file `/tmp/bad_email.eml`
Enable debug mode and start Mailscanner.
`/usr/lib/MailScanner/init/ms-init start`
Send a email 
`cat tmp/bad_email.eml | sendmail root@centos7.local`

Mailscanner stoped with error: 
`UTF-16:Unrecognised BOM 4e00 at /usr/local/share/perl5/MIME/WordDecoder.pm line 616.`

In Postfix directory `/var/spool/postfix/hold` there is a file with a binary content:
`CO           1140             213               1               0            1140T^Q1554901645 136371A^Vcreate_time=1554901645A^Urewrite_context=localF^DrootS^Proot@local.localO^Rroot@centos7.localR^Rroot@centos7.localM^@N3Received: by centos7.local (Postfix, from userid 0)N7    id 256148B4784; Wed, 10 Apr 2019 15:07:25 +0200 (CEST)NESCFrom: <noreply@email.local>N^VTo: <test@email.local>NFSubject: =?utf-16?B?TgBhAHMAdABhAHYAZQBuAO0AIABvAHAAcgDhAHYAbgAbAW4A?=NF =?utf-16?B?7QAsACAAcABvAH4BYQBkAGEAdgBlAGsAIABTAGgAYQByAGUAUABvAGkA?=NB =?utf-16?B?bgB0ACAALQAgAEEAcABsAGkAawBhAGMAZQAgAE0AUwBTAFEATAA=?=N*Content-Type: text/plain; charset="utf-16"N!Content-Transfer-Encoding: base64N6Message-Id: <20190410130725.256148B4784@centos7.local>N,Date: Wed, 10 Apr 2019 15:07:25 +0200 (CEST)N^@NLRABvAGIAcgD9ACAAZABlAG4ALAAgAAoACgBWAGEAYQFlACAAfgHhAGQAbwBzAHQAIAAwADEAMgAzNLADQAIABkAG8AIABhAHAAbABpAGsAYQBjAGUAIABNAFMAUwBRAEwAIABiAHkAbABhACAAdgB5AFkBNLZQBhAWUAbgBhAC4AIABQAHIAbwAgAGQAbwBrAG8AbgANAWUAbgDtACAAcAByAG8AYwBlAHMAdQAgNLAGoAZQAgAG4AZQB6AGIAeQB0AG4A6QAgAHMAZQAgAHoAbgBvAHYAdQAgAHAAWQFpAGgAbADhAHMANLaQB0ACAAZABvACAAVwBpAG4AZABvAHcAcwAuAAoACgBWACAAcABZAe0AcABhAGQAGwEgAG4AZQBqNLAGEAcwBuAG8AcwB0AO0AIABuAOEAcwAgAGsAbwBuAHQAYQBrAHQAdQBqAHQAZQAgAG4AYQAgAG4ANLYQBhAWUAbQAgAGUAbQBhAGkAbAB1AC4ACgAKAFMAIABwAG8AegBkAHIAYQB2AGUAbQAsAAoACgBJN AFQAIABIAGUAbABwAGQAZQBzAGsACgA=N^@X^@E^@`

Is the mailscanner behavior the same for you?

**Comment by shawniverson** [comment]
@jtempir Okay this helps.  Let me run a test using your steps.  I am using the milter so my steps are different from yours.
