### ISSUE TITLE
ms-init crash

### ISSUE THREAD

**Issue by fwittekind4** [MailScanner/v5#71]
When cron job tried to restart mailscanner, got this:

/
-/usr/lib/MailScanner/init/ms-init: line 489: [: -eq: unary operator expected
MailScanner failed to start ... doh!

Adding dead pid detection code to restart section of ms-init seems to correct issue.

**Comment by shawniverson** [comment]
This should be resolved in commit 66c929ba82b4171890a13544b60f89b67870e329

**Comment by fwittekind4** [comment]
That didn't fix it.  Copied ms-init from git yesterday, and still get the same error message.
PID file is still present hours later.

**Comment by shawniverson** [comment]
Can you share me exact the steps to reproduce?  I want to make sure that the dead pid detection code is an appropriate fix for this issue.

**Comment by fwittekind4** [comment]
CentOS 7 
MailScanner-5.0.6-2
Happens when /etc/cron.daily/mailscanner runs
Built RPM from copy of git repo, after commit 31b4f5af4f1c8886df67eb1217e6cb2aa81b6552 (7/24/2017)

commit 31b4f5af4f1c8886df67eb1217e6cb2aa81b6552

Snippet from email from cron job output:
File updated.
Restarting MailScanner ...

\
|
<Removing part of this as it's quite long>
|
/
-/usr/lib/MailScanner/init/ms-init: line 489: [: -eq: unary operator expected
MailScanner failed to start ... doh!

**Comment by philrandal** [comment]
That'll happen if the .pid file is still there after waiting 40 seconds for the stop to complete and it falls through the bottom of the loop waiting for the .pid file to vanish.

How long does it take to stop MailScanner in your setup?

**Comment by shawniverson** [comment]
@philrandal Yes, arrived to the same conclusion as well.  We need to handle this logic path as well, regardless.

**Comment by shawniverson** [comment]
@fwittekind4  Can you test PR #74 ?

**Comment by shawniverson** [comment]
@fwittekind4 Here's the raw link for your convenience https://raw.githubusercontent.com/shawniverson/v5/132adca2c4ffd1459c38bec3c957e856f6153184/common/usr/lib/MailScanner/init/ms-init

**Comment by fwittekind4** [comment]
Sorry for delay...   I just installed the new version of ms-init, I'll let you know results when I know them.

**Comment by fwittekind4** [comment]
MailScanner has stayed running for 2 days, so far so good.

**Comment by shawniverson** [comment]
Excellent!  Keep me posted.  Plan to do final testing this weekend and then hopefully (finally) a real release for everybody :)

**Comment by fwittekind4** [comment]
Still no issues with the updated script.
